name: Workflow A

on:
    workflow_dispatch:
        inputs:
            listA:
                type: string
            listB:
                type: string

jobs:
    cd:
        name: cd
        runs-on: [ubuntu-latest]
            
        uses: 'EduardDranca/test-for-nested-workflows/.github/workflows/workflowB.yml@main'
        with:
            listA: ${{ inputs.listA }}
            listB: ${{ inputs.listB }}