name: Workflow A

on:
  workflow_dispatch:
    inputs:
      listA:
        description: ma-ta
        type: string
      listB:
        description: du-te
        type: string

jobs:
  cd:
    name: cd
    
    uses: EduardDranca/test-for-nested-workflows/.github/workflows/workflowB.yml@main
    with:
      listA: ${{ inputs.listA }}
      listB: ${{ inputs.listB }}
